import { BrandsType, Laptops } from "./type";

export const initialDataLaptops: Laptops = [
  {
    id: 1,
    brand: "Asus",
    model: "ROG Zephyrus G14",
    slug: "asus-rog-zephyrus-g14",
    cpu: "AMD Ryzen 7 7840HS",
    gpu: "NVIDIA GeForce RTX 4060",
    ram: "16GB DDR5",
    storage: "512GB SSD",
    display: "14-inch QHD 165Hz",
    battery: "76Wh",
    weight: "1.65kg",
    releaseYear: 2023,
    price: 18990000,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    brand: "Apple",
    model: "MacBook Air M2 13",
    slug: "apple-macbook-air-m2-13",
    cpu: "Apple M2",
    gpu: "Apple M2 GPU (10-core)",
    ram: "8GB Unified Memory",
    storage: "256GB SSD",
    display: "13.6-inch Liquid Retina",
    battery: "52.6Wh",
    weight: "1.24kg",
    releaseYear: 2022,
    price: 15999000,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3,
    brand: "Lenovo",
    model: "Legion 5 Pro",
    slug: "lenovo-legion-5-pro",
    cpu: "AMD Ryzen 7 6800H",
    gpu: "NVIDIA GeForce RTX 3070 Ti",
    ram: "16GB DDR5",
    storage: "1TB SSD",
    display: "16-inch WQXGA 165Hz",
    battery: "80Wh",
    weight: "2.49kg",
    releaseYear: 2022,
    price: 24999000,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 4,
    brand: "Acer",
    model: "Swift X 14",
    slug: "acer-swift-x-14",
    cpu: "Intel Core i7-13700H",
    gpu: "NVIDIA GeForce RTX 4050",
    ram: "16GB LPDDR5",
    storage: "512GB SSD",
    display: "14-inch OLED 2.8K",
    battery: "59Wh",
    weight: "1.4kg",
    releaseYear: 2023,
    price: 17499000,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5,
    brand: "HP",
    model: "Victus 15",
    slug: "hp-victus-15",
    cpu: "Intel Core i5-12500H",
    gpu: "NVIDIA GeForce GTX 1650",
    ram: "8GB DDR4",
    storage: "512GB SSD",
    display: "15.6-inch FHD 144Hz",
    battery: "52.5Wh",
    weight: "2.29kg",
    releaseYear: 2023,
    price: 10999000,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6,
    brand: "Dell",
    model: "XPS 13 Plus",
    slug: "dell-xps-13-plus",
    cpu: "Intel Core i7-1360P",
    gpu: "Intel Iris Xe",
    ram: "16GB LPDDR5",
    storage: "1TB SSD",
    display: "13.4-inch OLED 3.5K",
    battery: "55Wh",
    weight: "1.26kg",
    releaseYear: 2023,
    price: 27999000,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7,
    brand: "Asus",
    model: "TUF Gaming F15",
    slug: "asus-tuf-gaming-f15",
    cpu: "Intel Core i7-12700H",
    gpu: "NVIDIA GeForce RTX 3060",
    ram: "16GB DDR4",
    storage: "512GB SSD",
    display: "15.6-inch FHD 144Hz",
    battery: "56Wh",
    weight: "2.2kg",
    releaseYear: 2022,
    price: 16999000,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 8,
    brand: "Apple",
    model: "MacBook Pro M2 14",
    slug: "apple-macbook-pro-m2-14",
    cpu: "Apple M2 Pro",
    gpu: "Apple M2 Pro GPU (16-core)",
    ram: "16GB Unified Memory",
    storage: "512GB SSD",
    display: "14.2-inch Liquid Retina XDR",
    battery: "70Wh",
    weight: "1.6kg",
    releaseYear: 2023,
    price: 32999000,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 9,
    brand: "Lenovo",
    model: "ThinkPad X1 Carbon Gen 11",
    slug: "lenovo-thinkpad-x1-carbon-gen-11",
    cpu: "Intel Core i7-1355U",
    gpu: "Intel Iris Xe",
    ram: "16GB LPDDR5",
    storage: "1TB SSD",
    display: "14-inch WUXGA",
    battery: "57Wh",
    weight: "1.12kg",
    releaseYear: 2023,
    price: 28999000,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 10,
    brand: "MSI",
    model: "Katana 15",
    slug: "msi-katana-15",
    cpu: "Intel Core i7-13620H",
    gpu: "NVIDIA GeForce RTX 4070",
    ram: "16GB DDR5",
    storage: "1TB SSD",
    display: "15.6-inch QHD 165Hz",
    battery: "53.5Wh",
    weight: "2.25kg",
    releaseYear: 2024,
    price: 25999000,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 11,
    brand: "Acer",
    model: "Aspire 5",
    slug: "acer-aspire-5",
    cpu: "Intel Core i5-1235U",
    gpu: "Intel Iris Xe",
    ram: "8GB DDR4",
    storage: "512GB SSD",
    display: "15.6-inch FHD",
    battery: "50Wh",
    weight: "1.77kg",
    releaseYear: 2022,
    price: 8999000,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 12,
    brand: "HP",
    model: "EliteBook 840 G10",
    slug: "hp-elitebook-840-g10",
    cpu: "Intel Core i7-1355U",
    gpu: "Intel Iris Xe",
    ram: "16GB DDR5",
    storage: "512GB SSD",
    display: "14-inch WUXGA",
    battery: "51Wh",
    weight: "1.36kg",
    releaseYear: 2023,
    price: 23999000,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 13,
    brand: "Asus",
    model: "Zenbook 14 OLED",
    slug: "asus-zenbook-14-oled",
    cpu: "Intel Core i7-1360P",
    gpu: "Intel Iris Xe",
    ram: "16GB LPDDR5",
    storage: "1TB SSD",
    display: "14-inch OLED 2.8K",
    battery: "75Wh",
    weight: "1.39kg",
    releaseYear: 2023,
    price: 19999000,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 14,
    brand: "Lenovo",
    model: "IdeaPad Slim 5",
    slug: "lenovo-ideapad-slim-5",
    cpu: "AMD Ryzen 5 7530U",
    gpu: "AMD Radeon Graphics",
    ram: "16GB DDR4",
    storage: "512GB SSD",
    display: "14-inch WUXGA",
    battery: "56Wh",
    weight: "1.46kg",
    releaseYear: 2023,
    price: 10999000,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 15,
    brand: "Dell",
    model: "Inspiron 14",
    slug: "dell-inspiron-14",
    cpu: "Intel Core i5-1335U",
    gpu: "Intel Iris Xe",
    ram: "16GB DDR4",
    storage: "512GB SSD",
    display: "14-inch FHD",
    battery: "54Wh",
    weight: "1.54kg",
    releaseYear: 2023,
    price: 11999000,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 16,
    brand: "MSI",
    model: "Prestige 14 Evo",
    slug: "msi-prestige-14-evo",
    cpu: "Intel Core i7-13700H",
    gpu: "Intel Iris Xe",
    ram: "16GB LPDDR5",
    storage: "1TB SSD",
    display: "14-inch FHD+",
    battery: "52Wh",
    weight: "1.49kg",
    releaseYear: 2023,
    price: 18999000,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 17,
    brand: "Apple",
    model: "MacBook Air M1",
    slug: "apple-macbook-air-m1",
    cpu: "Apple M1",
    gpu: "Apple M1 GPU (7-core)",
    ram: "8GB Unified Memory",
    storage: "256GB SSD",
    display: "13.3-inch Retina",
    battery: "49.9Wh",
    weight: "1.29kg",
    releaseYear: 2020,
    price: 12999000,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 18,
    brand: "Asus",
    model: "ROG Flow X13",
    slug: "asus-rog-flow-x13",
    cpu: "AMD Ryzen 9 7940HS",
    gpu: "NVIDIA GeForce RTX 4070",
    ram: "32GB LPDDR5",
    storage: "1TB SSD",
    display: "13.4-inch QHD+ 165Hz",
    battery: "75Wh",
    weight: "1.3kg",
    releaseYear: 2024,
    price: 32999000,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 19,
    brand: "HP",
    model: "Pavilion Aero 13",
    slug: "hp-pavilion-aero-13",
    cpu: "AMD Ryzen 7 7735U",
    gpu: "AMD Radeon Graphics",
    ram: "16GB LPDDR5",
    storage: "512GB SSD",
    display: "13.3-inch WQXGA",
    battery: "43Wh",
    weight: "0.97kg",
    releaseYear: 2023,
    price: 13999000,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 20,
    brand: "Lenovo",
    model: "Yoga Slim 7 Pro",
    slug: "lenovo-yoga-slim-7-pro",
    cpu: "AMD Ryzen 7 7840S",
    gpu: "AMD Radeon 780M",
    ram: "16GB LPDDR5",
    storage: "1TB SSD",
    display: "14.5-inch 3K 120Hz",
    battery: "73Wh",
    weight: "1.39kg",
    releaseYear: 2023,
    price: 18999000,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 21,
    brand: "Dell",
    model: "G15 Gaming",
    slug: "dell-g15-gaming",
    cpu: "Intel Core i7-12700H",
    gpu: "NVIDIA GeForce RTX 3050",
    ram: "16GB DDR5",
    storage: "512GB SSD",
    display: "15.6-inch FHD 120Hz",
    battery: "56Wh",
    weight: "2.65kg",
    releaseYear: 2022,
    price: 14999000,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 22,
    brand: "Acer",
    model: "Nitro 5",
    slug: "acer-nitro-5",
    cpu: "AMD Ryzen 7 6800H",
    gpu: "NVIDIA GeForce RTX 3060",
    ram: "16GB DDR5",
    storage: "1TB SSD",
    display: "15.6-inch QHD 165Hz",
    battery: "57Wh",
    weight: "2.5kg",
    releaseYear: 2022,
    price: 17999000,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 23,
    brand: "Asus",
    model: "Vivobook Pro 16X",
    slug: "asus-vivobook-pro-16x",
    cpu: "Intel Core i9-13980HX",
    gpu: "NVIDIA GeForce RTX 4070",
    ram: "32GB DDR5",
    storage: "1TB SSD",
    display: "16-inch OLED 3.2K",
    battery: "90Wh",
    weight: "2.0kg",
    releaseYear: 2024,
    price: 34999000,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 24,
    brand: "HP",
    model: "OMEN 16",
    slug: "hp-omen-16",
    cpu: "Intel Core i7-13700HX",
    gpu: "NVIDIA GeForce RTX 4080",
    ram: "32GB DDR5",
    storage: "1TB SSD",
    display: "16.1-inch QHD 240Hz",
    battery: "83Wh",
    weight: "2.35kg",
    releaseYear: 2024,
    price: 39999000,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 25,
    brand: "Lenovo",
    model: "Legion Slim 7i",
    slug: "lenovo-legion-slim-7i",
    cpu: "Intel Core i9-13900H",
    gpu: "NVIDIA GeForce RTX 4070",
    ram: "32GB DDR5",
    storage: "1TB SSD",
    display: "16-inch 3.2K 165Hz",
    battery: "99Wh",
    weight: "2.0kg",
    releaseYear: 2024,
    price: 32999000,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const brands: BrandsType = [
  {
    name: "Asus",
    slug: "asus",
    imageUrl:
      "https://logos-world.net/wp-content/uploads/2020/07/Asus-Logo-1995-present.png",
    createdAt: new Date(),
  },
  {
    name: "Apple",
    slug: "apple",
    imageUrl:
      "https://logos-world.net/wp-content/uploads/2020/04/Apple-Logo.png",
    createdAt: new Date(),
  },
  {
    name: "Lenovo",
    slug: "lenovo",
    imageUrl:
      "https://logos-world.net/wp-content/uploads/2022/07/Lenovo-Logo.png",
    createdAt: new Date(),
  },
  {
    name: "Acer",
    slug: "acer",
    imageUrl:
      "https://logos-world.net/wp-content/uploads/2022/11/Acer-Logo.png",
    createdAt: new Date(),
  },
  {
    name: "HP",
    slug: "hp",
    imageUrl: "https://logos-world.net/wp-content/uploads/2020/11/HP-Logo.png",
    createdAt: new Date(),
  },
  {
    name: "Dell",
    slug: "dell",
    imageUrl: "https://logos-world.net/wp-content/uploads/2020/11/HP-Logo.png",
    createdAt: new Date(),
  },
  {
    name: "MSI",
    slug: "msi",
    imageUrl: "https://logos-world.net/wp-content/uploads/2020/11/MSI-Logo.png",
    createdAt: new Date(),
  },
];

export let examplePostLaptop = {
  brand: "Apple",
  model: "MacBook Pro M3 Max",
  cpu: "Apple M3 Max (14-core)",
  gpu: "Apple M3 Max (30-core GPU)",
  ram: "36GB Unified Memory",
  storage: "1TB SSD",
  display: "14.2-inch Liquid Retina XDR",
  battery: null,
  weight: null,
  releaseYear: 2024,
  price: 55999000,
};
