import { Laptops } from "./schema";

export let initialData: Laptops = [
  {
    id: 1,
    brand: "Asus",
    model: "ROG Zephyrus G14",
    slug: "asus-rog-zephyrus-g14",
    cpu: "AMD Ryzen 7 7840HS",
    gpu: "NVIDIA GeForce RTX 4060",
    ram: "16GB DDR5",
    storage: "512GB SSD",
    display: "14-inch QHD 165Hz",
    battery: "76Wh",
    weight: "1.65kg",
    releaseYear: 2023,
    price: 18990000,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    brand: "Apple",
    model: "MacBook Air M2 13",
    slug: "apple-macbook-air-m2-13",
    cpu: "Apple M2",
    gpu: "Apple M2 GPU (10-core)",
    ram: "8GB Unified Memory",
    storage: "256GB SSD",
    display: "13.6-inch Liquid Retina",
    battery: "52.6Wh",
    weight: "1.24kg",
    releaseYear: 2022,
    price: 15999000,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3,
    brand: "Lenovo",
    model: "Legion 5 Pro",
    slug: "lenovo-legion-5-pro",
    cpu: "AMD Ryzen 7 6800H",
    gpu: "NVIDIA GeForce RTX 3070 Ti",
    ram: "16GB DDR5",
    storage: "1TB SSD",
    display: "16-inch WQXGA 165Hz",
    battery: "80Wh",
    weight: "2.49kg",
    releaseYear: 2022,
    price: 24999000,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 4,
    brand: "Acer",
    model: "Swift X 14",
    slug: "acer-swift-x-14",
    cpu: "Intel Core i7-13700H",
    gpu: "NVIDIA GeForce RTX 4050",
    ram: "16GB LPDDR5",
    storage: "512GB SSD",
    display: "14-inch OLED 2.8K",
    battery: "59Wh",
    weight: "1.4kg",
    releaseYear: 2023,
    price: 17499000,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5,
    brand: "HP",
    model: "Victus 15",
    slug: "hp-victus-15",
    cpu: "Intel Core i5-12500H",
    gpu: "NVIDIA GeForce GTX 1650",
    ram: "8GB DDR4",
    storage: "512GB SSD",
    display: "15.6-inch FHD 144Hz",
    battery: "52.5Wh",
    weight: "2.29kg",
    releaseYear: 2023,
    price: 10999000,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
